### ISSUE TITLE
Re building on openSUSE

### ISSUE THREAD

**Issue by Ayamikhan** [xeyownt/xseticon#14]
This is not an issue.

I cannot find another way to message you.

To build on openSUSE Leap 15.5, 
I needed to install gd-devel,
 
sudo zypper in gd-devel

Other dependencies were already present. 

Your hint command line works fine 
for XTerm, in WSL, on Windows 10.

Thank you, 

Aya.

**Comment by xeyownt** [comment]
Thanks for reporting.

I've added your line to the basic instructions ;-)

**Comment by Ayamikhan** [comment]
You are welcome. 

I should have waited until I was not tired.
The dependencies I already had installed are :

sudo zypper in libXmu-devel 
sudo zypper in glib2-devel 

Thank you again.

**Comment by Ayamikhan** [comment]
Or, 
sudo zypper in libXmu-devel glib2-devel gd-devel

**Comment by xeyownt** [comment]
Updated ;-)
