### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by brlin-tw** [xeyownt/xseticon#3]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on many GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a working snap on the Snap Store](https://snapcraft.io/xseticon), you may try it by running the following commands after [installing snapd](https://docs.snapcraft.io/installing-snapd/6735):
 
    sudo snap install xseticon

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://github.com/Lin-Buo-Ren/xseticon-snap), the [documentation](https://docs.snapcraft.io), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by xeyownt** [comment]
Hi Lin-Buo-Ren,

I tried your snap install, and this works for me. 
So I guess this is enough for me to merge your patch... which I just did ;-)

But I'm afraid I don't have much more time to allocate than this.

**Comment by brlin-tw** [comment]
Great!

> I'm afraid I don't have much more time to allocate than this.

That's fine, in that case, I'll set up a Launchpad code import to build the snap from this repository periodically.  Thanks for your consideration!
