### ISSUE TITLE
On Debian Buster, the package libglib2.0-dev is required

### ISSUE THREAD

**Issue by andrewgreenberg** [xeyownt/xseticon#5]
On Debian Buster (current testing distro), I got the error:

```
~/tools/xseticon$ make
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found

```
Installing libglib2.0-dev (`sudo apt install libglib2.0-dev`) fixed it. Thought you should add that dependency to the README.

Thanks for this handy piece of code!

**Comment by xeyownt** [comment]
Thanks for notifying. I just added the dependency.
